<a href="https://colab.research.google.com/github/imnirmilshah/INSIGHT-CODING-CHALLENGE/blob/master/ANN_Churn_modeling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



```

```

#Step 1: Installtion

In [135]:
#installing the tensorflow
pip install tensorflow-gpu

In [0]:
import tensorflow as tf


In [55]:
#Printing the current version on which we are working on
print(tf.__version__)

2.0.0


In [0]:
import numpy as np
import pandas as pd


# Step 2: Data Preprocessing

In [137]:
#In which directory we are working 
!ls

Churn_Modelling.csv  sample_data


In [0]:
# Reading the data using pandas
data=pd.read_csv("Churn_Modelling.csv")

In [140]:
data

RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10000 rows x 14 columns]

In [141]:
#for showing the top 5 rows of the data
data.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [142]:
len(data.columns)

14

In [0]:
#It is used for selecting the particular set of columns 
#from 3 to 13(feature selection)
x=data.iloc[:,3:13]

In [63]:
x

CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0             619    France  Female  ...          1               1        101348.88
1             608     Spain  Female  ...          0               1        112542.58
2             502    France  Female  ...          1               0        113931.57
3             699    France  Female  ...          0               0         93826.63
4             850     Spain  Female  ...          1               1         79084.10
...           ...       ...     ...  ...        ...             ...              ...
9995          771    France    Male  ...          1               0         96270.64
9996          516    France    Male  ...          1               1        101699.77
9997          709    France  Female  ...          0               1         42085.58
9998          772   Germany    Male  ...          1               0         92888.52
9999          792    France  Female  ...          1               0         38190.78

[10000 rows x 10 columns]

In [0]:
# As the column Exited is dependent on the behaviour of x columns
#(That the customer is still the part yes or no)
y=data['Exited']

In [65]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [66]:
# for knowing the datatypes and which we have to change.So, ANN can understand .
#  you can see the Geography and Gender are object which needed to be change
x.dtypes

CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
dtype: object

In [0]:
#label encoder is used for converting categorical into numerical so that the
#computer can understand.
# geography has france which gets converted into 0, spain into 1 ..continues..
from sklearn.preprocessing import LabelEncoder


In [0]:
label1=LabelEncoder()
x['Geography']=label1.fit_transform(x['Geography'])

In [0]:
# same with gender female-0 ,male -1 , or vice-versa
label2=LabelEncoder()
x['Gender']=label2.fit_transform(x['Gender'])

In [70]:
x

CreditScore  Geography  ...  IsActiveMember  EstimatedSalary
0             619          0  ...               1        101348.88
1             608          2  ...               1        112542.58
2             502          0  ...               0        113931.57
3             699          0  ...               0         93826.63
4             850          2  ...               1         79084.10
...           ...        ...  ...             ...              ...
9995          771          0  ...               0         96270.64
9996          516          0  ...               1        101699.77
9997          709          0  ...               1         42085.58
9998          772          1  ...               0         92888.52
9999          792          0  ...               0         38190.78

[10000 rows x 10 columns]

In [0]:
# we use one hot encoder so that computer can understand that male and female 
#are not higher or lower(as we denoted in label encoder) its just they are different.
from sklearn.preprocessing import OneHotEncoder 


In [72]:
onehotencoder = OneHotEncoder(categorical_features = [1]) 
x= onehotencoder.fit_transform(x).toarray()



/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [73]:
x

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [74]:
onehotencoder = OneHotEncoder(categorical_features = [2]) 
x = onehotencoder.fit_transform(x).toarray()

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [75]:
x

array([[1.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [76]:
x.shape

(10000, 13)

In [0]:
#For splitting the training and the test data.
#test size=20% , train=80%.. u can also do 30/70
#random state =0 .. so it can be same for all
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [0]:
#(variable-mean)/standard deviation it does this so that it can be easy 
#to reach the gradient descent 
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [79]:
x_train

array([[-1.74309049,  1.74309049, -1.01460667, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 0.57369368, -0.57369368, -1.01460667, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.57369368, -0.57369368,  0.98560362, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.57369368, -0.57369368,  0.98560362, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.74309049,  1.74309049, -1.01460667, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 0.57369368, -0.57369368, -1.01460667, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [80]:
x_test

array([[ 0.57369368, -0.57369368, -1.01460667, ...,  0.64259497,
         0.9687384 ,  1.61085707],
       [ 0.57369368, -0.57369368,  0.98560362, ...,  0.64259497,
        -1.03227043,  0.49587037],
       [-1.74309049,  1.74309049, -1.01460667, ...,  0.64259497,
         0.9687384 , -0.42478674],
       ...,
       [-1.74309049,  1.74309049, -1.01460667, ...,  0.64259497,
        -1.03227043,  0.71888467],
       [ 0.57369368, -0.57369368, -1.01460667, ...,  0.64259497,
         0.9687384 , -1.54507805],
       [ 0.57369368, -0.57369368, -1.01460667, ...,  0.64259497,
        -1.03227043,  1.61255917]])

# Step 3: Creating Dense layer

In [0]:
model=tf.keras.models.Sequential()


In [0]:
#input dimension and layers
model.add(tf.keras.layers.Dense(units=6,activation='relu',input_dim=13))

In [0]:
#second layer(hidden layer)
model.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [0]:
#output
model.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [0]:
#Compiling the model
# Adam changes the weight when it propogates back and forth by reaching near to G.D
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])


In [129]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_12 (Dense)             (None, 6)                 84        
_________________________________________________________________
dense_13 (Dense)             (None, 6)                 42        
_________________________________________________________________
dense_14 (Dense)             (None, 1)                 7         
Total params: 133
Trainable params: 133
Non-trainable params: 0
_________________________________________________________________


In [0]:
y_train=np.asarray(y_train)

# Step 4: Training Model

In [131]:
#epochs means number of times it performs backward and forward propogation.
model.fit(x_train,y_train, batch_size=10,epochs=20)


Train on 8000 samples
Epoch 1/20
8000/8000 [==============================] - 2s 262us/sample - loss: 0.5176 - accuracy: 0.7678
Epoch 2/20
8000/8000 [==============================] - 2s 192us/sample - loss: 0.4282 - accuracy: 0.8177
Epoch 3/20
8000/8000 [==============================] - 1s 187us/sample - loss: 0.4049 - accuracy: 0.8335
Epoch 4/20
8000/8000 [==============================] - 1s 183us/sample - loss: 0.3856 - accuracy: 0.8443
Epoch 5/20
8000/8000 [==============================] - 1s 187us/sample - loss: 0.3694 - accuracy: 0.8491
Epoch 6/20
8000/8000 [==============================] - 2s 191us/sample - loss: 0.3610 - accuracy: 0.8521
Epoch 7/20
8000/8000 [==============================] - 2s 194us/sample - loss: 0.3560 - accuracy: 0.8547
Epoch 8/20
8000/8000 [==============================] - 2s 202us/sample - loss: 0.3531 - accuracy: 0.8546
Epoch 9/20
8000/8000 [==============================] - 2s 202us/sample - loss: 0.3508 - accuracy: 0.8555
Epoch 10/20
8000/8000 [=

(8000, 13)

# Step 5: Model evaluate and prediction

In [132]:
test_loss, test_acc = model.evaluate(x_test,y_test.to_numpy())

2000/1 [================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

In [134]:
print("test_acc:{}".format(test_acc))

test_acc:0.8539999723434448
